import type { Api } from '../types';

export const mockApis: Api[] = [
  {
    id: '1',
    slug: 'payments-api',
    name: 'Payments API',
    description:
      'Initier, capturer et rembourser des paiements en temps réel sur tous les rails (SEPA, instant, carte).',
    domain: 'payments',
    protocol: 'REST',
    version: 'v3.2',
    status: 'stable',
    score: 92,
    consumersCount: 24,
    updatedAt: '2026-04-28',
    owner: { team: 'Team Payments', entity: 'BPCE Digital' },
    authMethods: ['OAuth2', 'API Key'],
    tags: ['psd2', 'sepa', 'real-time', 'partner-facing'],
  },
  {
    id: '2',
    slug: 'customer-identity-api',
    name: 'Customer Identity API',
    description:
      'Gérer les profils clients : création, lecture, mise à jour, anonymisation conforme RGPD.',
    domain: 'identity',
    protocol: 'REST',
    version: 'v2.5',
    status: 'stable',
    score: 88,
    consumersCount: 21,
    updatedAt: '2026-04-15',
    owner: { team: 'Team Identity', entity: 'BPCE Digital' },
    authMethods: ['OAuth2'],
    tags: ['gdpr', 'partner-facing', 'internal'],
  },
  {
    id: '3',
    slug: 'account-statements-api',
    name: 'Account Statements API',
    description:
      'Récupérer les relevés et l\'historique consolidé de tous les comptes d\'un client.',
    domain: 'accounts',
    protocol: 'REST',
    version: 'v2.1',
    status: 'stable',
    score: 85,
    consumersCount: 19,
    updatedAt: '2026-03-30',
    owner: { team: 'Team Customer Data', entity: 'BPCE Digital' },
    authMethods: ['OAuth2', 'mTLS'],
    tags: ['psd2', 'gdpr', 'partner-facing'],
  },
  {
    id: '4',
    slug: 'kyc-verification-api',
    name: 'KYC Verification API',
    description:
      'Vérifier l\'identité, la conformité AML et le scoring KYC à l\'ouverture d\'un compte.',
    domain: 'kyc',
    protocol: 'REST',
    version: 'v1.8',
    status: 'stable',
    score: 80,
    consumersCount: 14,
    updatedAt: '2026-03-12',
    owner: { team: 'Team Risk', entity: 'BPCE Digital' },
    authMethods: ['mTLS', 'OAuth2'],
    tags: ['aml', 'gdpr', 'internal'],
  },
  {
    id: '5',
    slug: 'transaction-search-api',
    name: 'Transaction Search API',
    description:
      'Rechercher et filtrer les transactions sur tous les comptes via une couche GraphQL unifiée.',
    domain: 'transactions',
    protocol: 'GraphQL',
    version: 'v1.4',
    status: 'stable',
    score: 78,
    consumersCount: 12,
    updatedAt: '2026-02-22',
    owner: { team: 'Team Customer Data', entity: 'BPCE Digital' },
    authMethods: ['OAuth2'],
    tags: ['gdpr', 'real-time', 'partner-facing'],
  },
  {
    id: '6',
    slug: 'cards-management-api',
    name: 'Cards Management API',
    description:
      'Émettre, suspendre, plafonner et configurer les cartes bancaires en libre-service.',
    domain: 'cards',
    protocol: 'REST',
    version: 'v2.0',
    status: 'stable',
    score: 75,
    consumersCount: 10,
    updatedAt: '2026-02-08',
    owner: { team: 'Team Cards', entity: 'BPCE Digital' },
    authMethods: ['OAuth2', 'API Key'],
    tags: ['pci-dss', 'real-time', 'partner-facing'],
  },
  {
    id: '7',
    slug: 'beneficiary-management-api',
    name: 'Beneficiary Management API',
    description:
      'Ajouter, valider et plafonner les bénéficiaires de virement avec contrôles anti-fraude.',
    domain: 'payments',
    protocol: 'REST',
    version: 'v1.0',
    status: 'review',
    score: 68,
    consumersCount: 6,
    updatedAt: '2026-01-25',
    owner: { team: 'Team Payments', entity: 'BPCE Digital' },
    authMethods: ['OAuth2'],
    tags: ['sepa', 'gdpr', 'partner-facing'],
  },
  {
    id: '8',
    slug: 'notifications-api',
    name: 'Notifications API',
    description:
      'Diffuser les événements bancaires (push, email, SMS) aux applications consommatrices via flux AsyncAPI.',
    domain: 'notifications',
    protocol: 'AsyncAPI',
    version: 'v0.4',
    status: 'draft',
    score: 55,
    consumersCount: 3,
    updatedAt: '2025-12-18',
    owner: { team: 'Team Customer Data', entity: 'BPCE Innovation' },
    authMethods: ['mTLS'],
    tags: ['real-time', 'internal'],
  },
  {
    id: '9',
    slug: 'risk-scoring-api',
    name: 'Risk Scoring API',
    description:
      'Calculer un score de risque transactionnel en temps réel ou en batch pour la lutte anti-fraude.',
    domain: 'risk',
    protocol: 'REST',
    version: 'v0.2',
    status: 'draft',
    score: 48,
    consumersCount: 2,
    updatedAt: '2025-11-30',
    owner: { team: 'Team Risk', entity: 'BPCE Innovation' },
    authMethods: ['mTLS', 'OAuth2'],
    tags: ['aml', 'batch', 'internal'],
  },
  {
    id: '10',
    slug: 'legacy-auth-api',
    name: 'Legacy Auth API',
    description:
      'Ancien endpoint d\'authentification SAML/SOAP. À migrer vers Customer Identity API d\'ici fin 2026.',
    domain: 'identity',
    protocol: 'SOAP',
    version: 'v4.7',
    status: 'deprecated',
    score: 32,
    consumersCount: 1,
    updatedAt: '2025-11-08',
    owner: { team: 'Team Identity', entity: 'BPCE Digital' },
    authMethods: ['JWT'],
    tags: ['legacy', 'internal'],
  },
];
